from building import *

cwd  = GetCurrentDir()
objs = []
list = os.listdir(cwd)
calc = cwd + "../../embedded/calculator"
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
objs = objs + SConscript(os.path.join(calc, 'SConscript'))
Return('objs')
