import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.

srcx = Glob('Src/*.c')
src = []
for t in srcx:
    if t.name.find('template') == -1:
        src.append(t)
path = [cwd + '/Inc']

#CPPDEFINES = ['USE_HAL_DRIVER', rtconfig.STM32_TYPE]
CPPDEFINES = ['USE_HAL_DRIVER']
group = DefineGroup('STM32F7xx_HAL_Driver', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
